name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
@@ -15,10 +13,10 @@ jobs:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name Anshul-hub69
          git config user.email anshulsharma08012007@gmail.com
          git add -A .
          git commit -m "generated"
          git push
